name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Linter
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn dist
      - name: storybook and publish
        run: |
          yarn build-storybook
        env:
          CI: true
      - uses: raulanatol/slack-message-github-action@v1.0.0
        env:
          WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_CHANNEL: cicd
          MESSAGE: "Compilation ends"
          STATUS: ${{job.status}}
