name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      #      - uses: actions/checkout@v1

      - uses: raulanatol/slack-messages-action@master
        env:
          WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          BOT_USERNAME: Chalmers
          SLACK_CHANNEL: remove
          ICON_EMOJI: "::chalmers::"
          MESSAGE: "test message"

#      - name: GitHub Action for Yarn
#        uses: Borales/actions-yarn@1.1.0
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - name: install, build lint and test
#        run: |
#          yarn install
#          yarn dist
#          yarn lint
#          yarn test
#
#      - name: storybook and publish
#        run: |
#          yarn build-storybook
#        env:
#          CI: true


